const colors = {
  BROWN_BG_PRIMARY: '#E5B84E',
  BROWN_BG_SECONDARY: '#C6A379',
  BROWN_BG_TERTIERY: '#ECD59F',
  BROWN_BG_DISABLED: '#EDE6D0',
  BROWN_ACCENT: '#C79C37',
  BROWN_TEXT: '#6A452A',
  BROWN_GRADIENT_START: '#E5B84E',
  BROWN_GRADIENT_END: '#FAD85C',
  BLACK_TEXT_PRIMARY: '#213345',
  BLACK_TEXT_SECONDARY: '#495766',
  BLACK_TEXT_TERTIERY: '#6F7984',
  GRAY_BACKGROUND_PRIMARY: '#E5E5EA',
  GRAY_BACKGROUND_SECONDARY: '#F4F1EF',
  GRAY_BACKGROUND_TERTIERY: '#DFDEDC',
  GRAY_BACKGROUND_DISABLED: '#F7F7F9',
  WHITE: '#FFFFFF',
  ERROR: '#FA7A53',
};

export default colors;
