const pathPrefix = 'Assets/Images/';

const images = {
  mhi: require(pathPrefix+'mhi.jpg'),
  cart: require(pathPrefix+'cart.png'),
  minus: require(pathPrefix+'minus.png'),
  plus: require(pathPrefix+'plus.png'),
  delete: require(pathPrefix+'delete.png'),
  delete_flat: require(pathPrefix+'delete_flat.png'),
  location: require(pathPrefix+'location.png'),
  add: require(pathPrefix+'add.png'),
  syncFailed: require(pathPrefix+'sync_failed.png'),
  back: require(pathPrefix+'left_arrow.png'),
  back_shadow: require(pathPrefix+'left_arrow_shadow.png'),
  mhi: require(pathPrefix+'logo_mhi.png'),
  check: require(pathPrefix+'check.png'),
  cashier: require(pathPrefix+'cashier.png'),
  home: require(pathPrefix+'home.png'),
  user: require(pathPrefix+'user.png'),
  needLogin: require(pathPrefix+'need-login.png'),
  edit: require(pathPrefix+'edit.png'),
  edit_small: require(pathPrefix+'edit_small.png'),
  history: require(pathPrefix+'history.png'),
  courier_shop: require(pathPrefix+'courier_shop.png'),
  shipping: require(pathPrefix+'shipping.png'),
  tracking: require(pathPrefix+'tracking.png'),
  sent: require(pathPrefix+'sent.png'),
  delivery: require(pathPrefix+'delivery.png'),
  search: require(pathPrefix+'search.png'),
  no_photo: require(pathPrefix+'no_photo.png'),
  cart_add: require(pathPrefix+'cart_add.png'),
  product_list: require(pathPrefix+'product_list.png'),
  error: require(pathPrefix+'error.png'),
  warning: require(pathPrefix+'warning.png'),
  veggie: require(pathPrefix+'veggie.png'),
  fruit: require(pathPrefix+'fruit.png'),
  horti: require(pathPrefix+'horti.png'),
  logout: require(pathPrefix+'logout.png'),
  bebas_peskim: require(pathPrefix+'bebas_peskim.png'),
  cross: require(pathPrefix+'cross.png'),
  farmer: require(pathPrefix+'farmer.png'),
  non_farmer: require(pathPrefix+'non_farmer.png'),
  customer: require(pathPrefix+'customer.png'),
  scholar: require(pathPrefix+'scholar.png'),
  map: require(pathPrefix+'map.png'),
  map_disabled: require(pathPrefix+'map_gray.png'),
  pin_marker: require(pathPrefix+'pin_marker.png'),
  check_flat: require(pathPrefix+'check_flat.png'),
  pinned: require(pathPrefix+'pinned.png'),
  undo: require(pathPrefix+'undo.png'),
  gps: require(pathPrefix+'gps.png'),
}

export default images
