export default {
  NO_DATA_FOUND: "Kami tidak bisa menemukan data yang Anda cari",
  GRAPHQL_ERROR_HEADER: "Maaf saat ini ada gangguan",
  GRAPHQL_ERROR_BODY: "Terjadi kesalahan teknis, silahkan kontak pengembang",
  NETWORK_ERROR_HEADER: "Maaf saat ini ada gangguan",
  NETWORK_ERROR_BODY: "Silahkan coba lagi atau tunggu beberapa saat",
  SAVE: "SIMPAN",
  RELOAD: "COBA LAGI",
  UPLOAD_PHOTO: "Unggah foto",
  TAKE_KTP_PHOTO: "Ambil foto KTP",
  TAKE_FACE_PHOTO: "Ambil foto muka",
  GO_TO_NEXT_FORM: "Selanjutnya",

  LOC_DENIED_POPUP_TITLE: "Gagal mendapatkan lokasi anda",
  LOC_DENIED_POPUP_BODY: "Perijinan lokasi telah ditolak",

  MONTH_JAN: "Januari",
  MONTH_FEB: "Februari",
  MONTH_MAR: "Maret",
  MONTH_APR: "April",
  MONTH_MAY: "Mei",
  MONTH_JUN: "Juni",
  MONTH_JUL: "Juli",
  MONTH_AUG: "Agustus",
  MONTH_SEP: "September",
  MONTH_OCT: "Oktober",
  MONTH_NOV: "Nopember",
  MONTH_DEC: "Desember",
};
